### PR TITLE
Bug 1181652 splice changes to support dual databases

### PR DESCRIPTION
**Pull request by oyiptong**
more at https://bugzilla.mozilla.org/show_bug.cgi?id=1181652

### CODE REVIEW

**Comment by ncloudioj** [comment]
@oyiptong shall we remove "hll" and "unique_counts" stuff in the ddl as well?

**Comment by oyiptong** [comment]
I removed them in this commit: https://github.com/oyiptong/splice/commit/839a06154cca6aa1f6aace90dd98c94645e8a1a8

Did I miss anything?

**Comment by ncloudioj** [comment]
r+ @oyiptong

**Pull request closed without merging**
