### PR TITLE
Unify time format to ISO8601

### PR DESCRIPTION
**Pull request by ncloudioj**
This PR intends to unify the time format for all SP2 models. See #142 .

**NOTE:** you might need to set the `timezone` for your Postgresql to 'UTC'. Otherwise, it'll automatically do the conversion regardless the timezone you've passed to it.
 
In your `postgresql.conf`, search `timezone` and replace it with 'UTC'. It's already configured properly in production.

### CODE REVIEW

**Comment by rlr** [comment]
Do we care about the coverage check? They seem to be stuck in pending recently

**Comment by rlr** [comment]
Otherwise, this looks good and tests pass. r+

**Comment by tspurway** [comment]
yep r+

**Comment by ncloudioj** [comment]
Yes, the coverage seems unhappy probably because of the front-end tests. I'll take a look at this as we do want to keep the coverage for the back-end part.

**Pull request closed without merging**
