### PR TITLE
Bug 1161192 - Implement frequency cap in splice

### PR DESCRIPTION
**Pull request by oyiptong**
tracked at https://bugzilla.mozilla.org/show_bug.cgi?id=1161192

This feature is optimizable. I.e. however way we mutate it, we should have a way to track how it has performed.

### CODE REVIEW

**Comment by tspurway** [comment]
@oyiptong are there db migrations in a separate branch?  could you submit those in a PR as well?

**Comment by oyiptong** [comment]
I forgot about the migrations. D'oh.

It's coming soon

**Comment by ncloudioj** [comment]
r+ @oyiptong

**Pull request closed without merging**
