### PR TITLE
Upgrade AngularJS to 1.4.5

### PR DESCRIPTION
**Pull request by ncloudioj**
Upgrading AngularJS to solve the unresponsive UI

### CODE REVIEW

**Comment by ncloudioj** [comment]
@rlr

**Comment by rlr** [comment]
Fixes the unresponsiveness of the calendar tool for me. r+

**Comment by ncloudioj** [comment]
wonder what's coveralls busy about here

**Comment by ncloudioj** [comment]
Close by commit d8d0aa743c8d08578f13004eb08b9f50c30a86fd

**Pull request closed without merging**
