### PR TITLE
Bug 1153249 make tests postgres compatible

### PR DESCRIPTION
**Pull request by oyiptong**
https://bugzilla.mozilla.org/show_bug.cgi?id=1153249

### CODE REVIEW

**Comment by oyiptong** [comment]
@tspurway r?

**Comment by oyiptong** [comment]
Sorry, I was playing around with the github mobile app

**Comment by tspurway** [comment]
r+ @oyiptong

**Comment by oyiptong** [comment]
Found that the UI for splice is not working. uploads are broken

**Comment by oyiptong** [comment]
actually, it was working. I forgot to migrate my database

**Pull request closed without merging**
