### PR TITLE
[bug 1189688] Implement Account API

### PR DESCRIPTION
**Pull request by rlr**
YAY!

r? @ncloudioj

### CODE REVIEW

**Comment by rlr** [comment]
all tests failed?!??! whaaaa

**Comment by rlr** [comment]
"Works on my machine." (TM)

:laughing:

**Comment by oyiptong** [comment]
It looks like it's a database issue. The app configuration may be wrong

**Comment by rlr** [comment]
Yeah. For some reason it is trying to run the tests on mozsplice_campaigns database. I am not sure how I could've triggered that with my changes. I'll have to figure out how the test environment is setup and all that.

**Comment by rlr** [comment]
I see the problem. The environment for tests are setup as a side effect to an import. So if the imports are in the wrong order, shit happens. That's kinda... gross... But we'll fix that later. In the meantime, `from tests.base import BaseTestCase` must be the first thing imported in test_*.py files.

**Comment by rlr** [comment]
YAY. Fixed that and added a FIXME comment. And fixed my flake8 issues. good to go for real now, r?

**Comment by ncloudioj** [comment]
Yes, I was bitten by the same issue last week. Let's fix it before it bugs other people again.

**Comment by oyiptong** [comment]
Yes, the import order is an artifact of using Flask.

It's pretty icky. It is the reason sometimes you see models imported in a local scope.

**Comment by ncloudioj** [comment]
r+ @rlr

**Comment by rlr** [comment]
fixes in the last commit ^. I'll squash and merge once they pass CI.

**Comment by rlr** [comment]
landed on splice2.0 branch: 9cbbb5244cd596d7283e25f8832a762d0a125486

**Pull request closed without merging**
