### PR TITLE
Separate dev dependencies and dependencies

### PR DESCRIPTION
**Pull request by k88hudson**
I think this would be a good idea so we can get an idea of what is actually going to be included in our front end js/css bundle.

### CODE REVIEW

**Comment by k88hudson** [comment]
what do you think @tkiethanom @rlr?

**Comment by k88hudson** [comment]
I also locked dependencies to specific versions to prevent unexpected bugs from happening on patch version updates. We can add greenkeeper or something to help with keeping them up to date

**Comment by tkiethanom** [comment]
Does the react stuff belong in dependencies?

**Comment by rlr** [comment]
:+1: for doing this

**Comment by k88hudson** [comment]
@tkiethanom yep! good call

**Comment by tkiethanom** [comment]
:+1: looks good to me. Thanks @k88hudson !

**Pull request merged**
