### PR TITLE
Make Clang happy on Mac OS

### PR DESCRIPTION
**Pull request by ncloudioj**
r? @oyiptong

### CODE REVIEW

**Comment by oyiptong** [comment]
Can you just set the CFLAGS environment variable at the beginning of the file?

**Comment by oyiptong** [comment]
i.e. 
```
export CFLAGS='-std=c99'
```
actually, it might be safer to set that variable only for development and not for production, i.e. not at the top of the file.

**Comment by oyiptong** [comment]
we probably use gcc in our jenkins build. i wonder if that flag will have any adverse effects

**Comment by ncloudioj** [comment]
Yes, I don't think we need this for the Linux box. So I just dropped an alias only for development.

**Comment by oyiptong** [comment]
how about an environment variable in development mode?

BTW, i just checked, gcc does support the `-std=c99` CFLAGS parameter

**Comment by ncloudioj** [comment]
No problem, new change pushed.

**Comment by oyiptong** [comment]
r+

**Pull request merged**
