### PR TITLE
Bug 1161196 add custom explanation

### PR DESCRIPTION
**Pull request by ncloudioj**
tracked at [1161196 - Add custom explanation](https://bugzilla.mozilla.org/show_bug.cgi?id=1161196)

This PR will add two fields to the "adgroup" table: "name" and "explanation", repectively.
Note that the "explanation" is a predefined template with 2 arguments as "%1$S" and "%2$S".

### CODE REVIEW

**Comment by oyiptong** [comment]
@ncloudioj can you please add a test for input sanitization?

**Comment by oyiptong** [comment]
nevermind, i see a test that does just that

**Comment by oyiptong** [comment]
At: https://github.com/ncloudioj/splice/blob/bug-1161196-add-custom-explanation/tests/test_ingest.py#L235

Can you move this test in a separate function?

**Comment by oyiptong** [comment]
r+ after the change

**Comment by ncloudioj** [comment]
Yep, it deserves a separate test.

**Comment by oyiptong** [comment]
Nan, can you please merge --squash?

**Pull request merged**
