### PR TITLE
Bug 1159891 display environment in splice to prevent deployment errors

### PR DESCRIPTION
**Pull request by oyiptong**
We can prevent errors by displaying the environment

### CODE REVIEW

**Comment by oyiptong** [comment]
screen shot 2015-04-30 at 10 26 33
screen shot 2015-04-30 at 10 26 45

**Comment by oyiptong** [comment]
:-) I made it show the environment in dev as well in a subsequent commit

**Comment by emtwo** [comment]
r+ @oyiptong

**Pull request closed without merging**
