### PR TITLE
Bug 1156336 - UI to preview Adgroups

### PR DESCRIPTION
**Pull request by oyiptong**
Enable adgroups preview by parsing input

tracked on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1156336

### CODE REVIEW

**Comment by oyiptong** [comment]
Preview of collapsed default tiles:
splice-collapsed-default-tiles

Preview of collapsed locales:
splice-collapsed-locales

Preview of frecent sites:
splice-frecent-sites-preview

**Comment by oyiptong** [comment]
### Upcoming tiles preview
splice-upcoming-preview

**Comment by emtwo** [comment]
r+ @oyiptong

**Pull request closed without merging**
