### PR TITLE
Fix various issues in index_walk

### PR DESCRIPTION
**Pull request by ncloudioj**
This fixes following issues in the data migration script:
* generating default adgroup name as `adgroup_cpgm_%{campaign_id}`
* populating the `type` field for adgroups as either `suggested` or `directory`
* populating the `campaign_countries` table
* fixing various wrong target urls

### CODE REVIEW

**Comment by tspurway** [comment]
not sure why travis is complaining, but r+ otherwise

**Comment by oyiptong** [comment]
Here's the traceback:

======================================================================

> FAIL: Test the API endpoint for bulk upload
> 
> ----------------------------------------------------------------------
> 
> Traceback (most recent call last):
> 
>   File "/home/travis/build/oyiptong/splice/tests/api/test_tile_upload.py", line 110, in > test_bulk_upload_endpoint
> 
>     assert_equal(response.status_code, 200)
> 
> AssertionError: 400 != 200

**Comment by ncloudioj** [comment]
Oops, looking into it now.

**Comment by ncloudioj** [comment]
Hmm, weird. It hasn't changed any code but the migration script.

All tests got passed locally. Will merge it and see what happens.

**Pull request merged**
