### PR TITLE
Add OPTIONS and Content-Type to fully support CORS

### PR DESCRIPTION
**Pull request by ncloudioj**
* Add `OPTIONS` method for the CORS preflight check
* Add `Content-Type` for the `POST` method

### CODE REVIEW

**Comment by rlr** [comment]
makes sense.. those tests pass. r+!

**Comment by rlr** [comment]
now the coverage test isnt happy after that last commit

**Comment by ncloudioj** [comment]
yup, fixing it now.

**Comment by ncloudioj** [comment]
All looks good now, will merge it. Thank you @rlr for reviewing it, amigo.

**Pull request closed without merging**
