### PR TITLE
Refactor models and add fixture for testing

### PR DESCRIPTION
**Pull request by ncloudioj**
Refactor models:
1. add "status" to "tiles" table.
2. add "campaign_id" to "adgroups" table.

It also includes an updated fixture for testing purpose.

### CODE REVIEW

**Comment by rlr** [comment]
I'm curious why you had to edit migrations instead of create new ones? These haven't been deployed yet I guess?

**Comment by rlr** [comment]
Or looking closer, I guess you created a new migration and deleted an existing one. I guess the one deleted hadn't been deployed anywhere?

**Comment by rlr** [comment]
Other than those questions, this looks good to me.

**Comment by ncloudioj** [comment]
Nope, the old one was generated by our own Flask-Migrate branch. Now that we've upgraded it to 1.5.0, we'll stick to the official template. Also, it's not deployed yet.

**Comment by rlr** [comment]
makes sense! r+

**Pull request closed without merging**
