### PR TITLE
Add new campaigns to migration script

### PR DESCRIPTION
**Pull request by ncloudioj**

### CODE REVIEW

**Comment by k88hudson** [comment]
@ncloudioj LGTM. do we maybe want to merge this since we've been hitting the connection pool error a lot?

**Comment by tspurway** [comment]
r+

**Comment by k88hudson** [comment]
oops sorry commented on the wrong ticket, lol

**Comment by ncloudioj** [comment]
@k88hudson for that one, we can merge it and then try it out on the dev server first. Still unsure if that patch will fix the issue.

**Pull request merged**
