### PR TITLE
Sp2 Front End Create Campaign, Ad Group, Tile Navigation

### PR DESCRIPTION
**Pull request by tkiethanom**
r? @rlr 

You can now Create Campaigns, Ad Groups and Tiles from the Navigation. Dropdowns to select parent Model now appear in the form.

Ad Group Channel removed, value is pulled from parent Campaign #237 

Now using react-select instead of select2 #240

### CODE REVIEW

**Comment by rlr** [comment]
When I try to load the app into the browser it errors out: `Uncaught SyntaxError: Unexpected token import`

The console spits this out:

```
ERROR in ./src/components/Campaigns/CampaignForm/CampaignForm.js
Module not found: Error: Cannot resolve module 'react-select/dist/react-select.min.css' in /Users/rlr/dev/splice/front_end/src/components/Campaigns/CampaignForm
 @ ./src/components/Campaigns/CampaignForm/CampaignForm.js 45:0-49

ERROR in ./src/components/Campaigns/CampaignForm/CampaignForm.js
Module not found: Error: Cannot resolve module 'react-select' in /Users/rlr/dev/splice/front_end/src/components/Campaigns/CampaignForm
 @ ./src/components/Campaigns/CampaignForm/CampaignForm.js 39:19-42

ERROR in ./src/components/AdGroups/AdGroupForm/AdGroupForm.js
Module not found: Error: Cannot resolve module 'react-select' in /Users/rlr/dev/splice/front_end/src/components/AdGroups/AdGroupForm
 @ ./src/components/AdGroups/AdGroupForm/AdGroupForm.js 33:19-42

ERROR in ./src/components/AdGroups/AdGroupForm/AdGroupForm.js
Module not found: Error: Cannot resolve module 'react-select/dist/react-select.min.css' in /Users/rlr/dev/splice/front_end/src/components/AdGroups/AdGroupForm
 @ ./src/components/AdGroups/AdGroupForm/AdGroupForm.js 39:0-49

ERROR in ./src/components/Tiles/TileForm/TileForm.js
Module not found: Error: Cannot resolve module 'react-select' in /Users/rlr/dev/splice/front_end/src/components/Tiles/TileForm
 @ ./src/components/Tiles/TileForm/TileForm.js 35:19-42

ERROR in ./src/components/Tiles/TileForm/TileForm.js
Module not found: Error: Cannot resolve module 'react-select/dist/react-select.min.css' in /Users/rlr/dev/splice/front_end/src/components/Tiles/TileForm
 @ ./src/components/Tiles/TileForm/TileForm.js 48:0-49
```

**Comment by rlr** [comment]
(I did do a fresh `npm install` before running it)

**Comment by rlr** [comment]
It looks like you didnt add 'react-select` to `package.json`. `$ npm install react-select` fixes the error

**Comment by rlr** [comment]
If you look at those commits individually, they are a mess. Instead of merging from upstream you should be rebasing.

**Comment by tkiethanom** [comment]
Yea I'm having issues with squashing. I might have lost some changes too because of conflicts.

**Pull request closed without merging**
